apiVersion: v1
kind: Service
metadata:
  name: stream-greeter
spec:
  selector:
    app: stream-greeter
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-greeter
spec:
  selector:
    matchLabels:
      app: stream-greeter
  template:
    metadata:
      labels:
        app: stream-greeter
    spec:
      containers:
      - name: greeter
        image: will be updated by build script
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "my-cluster-kafka-external-bootstrap.kafka:9094"
        # resources:
        #   limits:
        #     memory: "2000m"
        #     cpu: "2Gi"
        #   requests:
        #     memory: "1000m"
        #     cpu: "1Gi"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080

